<?php
/**
 * Created by PhpStorm.
 * User: Edwin
 * Date: 20/02/2018
 * Time: 21:27
 */

$root = $_SERVER['DOCUMENT_ROOT'] . '/inelcom';
require("$root/modelo/general.php");

class general extends General_modelo
{
    public function getCss($title = null)
    {
        return parent::getCss($title);
    }

    public function getLeftMenu($data)
    {
        return parent::getLeftMenu($data);
    }

    public function getTopBar()
    {
        return parent::getTopBar(); // TODO: Change the autogenerated stub
    }

    public function getScript()
    {
        return parent::getScript(); // TODO: Change the autogenerated stub
    }

    public function getRubroList()
    {
        return parent::getRubroList(); // TODO: Change the autogenerated stub
    }

    public function getStatusList()
    {
        return parent::getStatusList(); // TODO: Change the autogenerated stub
    }

    public function getTitulo($title, $placeholder)
    {
        return parent::getTitulo($title, $placeholder); // TODO: Change the autogenerated stub
    }

    public function getFooter()
    {
        return parent::getFooter(); // TODO: Change the autogenerated stub
    }

    public function getPerfilList()
    {
        return parent::getPerfilList(); // TODO: Change the autogenerated stub
    }

    public function agregarComentario($data)
    {
        return parent::agregarComentario($data);
    }

    public function agregarSituacion($data)
    {
        return parent::agregarSituacion($data);
    }

    public function getInfoSIGO($id)
    {
        return parent::getInfoSIGO($id);
    }
}
