<?php
/**
 * Created by PhpStorm.
 * User: Edwin
 * Date: 08/03/2018
 * Time: 22:34
 */

$root = $_SERVER['DOCUMENT_ROOT'].'/inelcom';
require("$root/modelo/proyecto.php");

class proyecto extends Proyecto_modelo
{
    public function createProyecto($data = [])
    {
        return parent::createProyecto($data); // TODO: Change the autogenerated stub
    }

    public function getCodigoActual()
    {
        return parent::getCodigoActual(); // TODO: Change the autogenerated stub
    }

    public function listarProyectos($usuario)
    {
        return parent::listarProyectos($usuario); // TODO: Change the autogenerated stub
    }

    public function getDetalleProyecto($id)
    {
        return parent::getDetalleProyecto($id); // TODO: Change the autogenerated stub
    }

    public function actualizarStatus($id, $status)
    {
        parent::actualizarStatus($id, $status); // TODO: Change the autogenerated stub
    }
}