<?php
/**
 * Created by PhpStorm.
 * User: Edwin
 * Date: 05/03/2018
 * Time: 22:24
 */
$root = $_SERVER['DOCUMENT_ROOT'].'/inelcom';

require_once("$root/modelo/usuario.php");

class usuario extends Usuario_modelo
{
    public function leerUsuario($id)
    {
        return parent::leerUsuario($id);
    }

    public function registrarUsuario($data)
    {
        return parent::registrarUsuario($data); // TODO: Change the autogenerated stub
    }

    public function validarUsuario($data)
    {
        return parent::validarUsuario($data); // TODO: Change the autogenerated stub
    }


}